"""Pure value types shared across the engine.

These are deliberately dumb data holders — no IO, no model calls. `Compute` is the
honesty layer: every `Trace` carries the cost that produced it, and the runner sums
them, so an accuracy "lift" can never hide un-counted verifier compute (DESIGN.md
§4.2).
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Compute:
    """Resources spent producing a trace or a whole run. Counts *both* models."""

    policy_gen_tokens: int = 0
    policy_forward_calls: int = 0
    verifier_forward_calls: int = 0
    verifier_gen_tokens: int = 0
    wall_seconds: float = 0.0

    def __add__(self, other: Compute) -> Compute:
        return Compute(
            policy_gen_tokens=self.policy_gen_tokens + other.policy_gen_tokens,
            policy_forward_calls=self.policy_forward_calls + other.policy_forward_calls,
            verifier_forward_calls=self.verifier_forward_calls + other.verifier_forward_calls,
            verifier_gen_tokens=self.verifier_gen_tokens + other.verifier_gen_tokens,
            wall_seconds=self.wall_seconds + other.wall_seconds,
        )

    @property
    def total_tokens(self) -> int:
        """The headline compute axis: tokens generated by policy *and* verifier."""
        return self.policy_gen_tokens + self.verifier_gen_tokens


@dataclass(frozen=True)
class Problem:
    """One task to solve. Math problems carry a gold `answer`; code carries `tests`."""

    id: str
    prompt: str
    answer: str | None = None
    tests: tuple[str, ...] | None = None
    difficulty: str | None = None


@dataclass(frozen=True)
class Step:
    """A contiguous chunk of a reasoning trace that search can branch on / score."""

    text: str
    token_count: int


@dataclass
class Trace:
    """A (partial or complete) reasoning trace plus the compute that produced it."""

    steps: list[Step] = field(default_factory=list)
    final_answer: str | None = None
    compute: Compute = field(default_factory=Compute)

    @property
    def text(self) -> str:
        """Reconstruct the full reasoning text from its steps."""
        return "\n\n".join(s.text for s in self.steps)


@dataclass(frozen=True)
class Verdict:
    """The outcome verifier's judgement of a trace."""

    correct: bool
    detail: str = ""


@dataclass(frozen=True)
class Result:
    """One (problem × method) outcome row — the unit the report aggregates over."""

    problem_id: str
    method: str
    dataset: str
    correct: bool
    predicted: str | None
    gold: str | None
    compute: Compute
    difficulty: str | None = None
